# action.yml
name: "Semantic release"
description: 'This tool performs semantic release or returns value of next release version'
inputs:
  dry_run:  # if only version should be returned without releasing new version
    description: 'dry run'
    default: false
    required: false
  semantic_version:
    description: 'version of semantic-release to be used'
    required: true
outputs:
  new_release_version:
    description: 'Version of the new release'
    value: ${{ steps.semantic.outputs.version }}
  new_release_published:
    description: 'Whether a new release was published.'
    value: ${{ steps.semantic.outputs.new_release_published }}
runs:
  using: 'composite'
  steps:
    - id: semantic
      run: npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec;if [[ ${{ inputs.dry_run }} == true ]]; then npx semantic-release@${{ inputs.semantic_version }} --dry-run; else semantic-release@${{ inputs.semantic_version }};fi
      shell: bash
