name: "Semantic release"
description: "This tool performs semantic release or returns value of next release version"

inputs:
  dry_run:
    description: "dry run - if only version should be returned without releasing new version"
    default: false
    required: false

outputs:
  new_release_version:
    description: "Version of the new release"
    value: ${{ steps.semantic.outputs.version }}
  new_release_published:
    description: "Whether a new release was published"
    value: ${{ steps.semantic.outputs.new_release_published }}

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: install npm packages
      run: |
        cd ${{github.action_path}}
        npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec
    - id: semantic
      run: |
        if [[ ${{ inputs.dry_run }} == true ]]; 
          then npx semantic-release@20 --dry-run
        else 
          npx semantic-release@20
        fi
      shell: bash
