name: Release
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.6.23/scripts/download-actionlint.bash)
      - uses: pre-commit/action@v3.0.0

  new-release:
    name: Release new version of action
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          persist-credentials: false
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.SA_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SA_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Semantic release
        id: semantic
        uses: splunk/semantic-release-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
          GIT_AUTHOR_NAME: "srv-rr-github-token"
          GIT_AUTHOR_EMAIL: "srv-rr-github-token@users.noreply.github.com"
          GIT_COMMITTER_NAME: "srv-rr-github-token"
          GIT_COMMITTER_EMAIL: "srv-rr-github-token@users.noreply.github.com"
        with:
          extra_plugins: |
            @google/semantic-release-replace-plugin

  update-semver:
    name: Move Repository semver tags
    if: startsWith(github.ref, 'refs/tags/v')
    needs: new-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-update-semver@v1
