name: Release
on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.6.23/scripts/download-actionlint.bash)
      - uses: pre-commit/action@v3.0.0

  new-release:
    name: Release new version of action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          persist-credentials: false
      - name: Semantic release
        id: semantic
        uses: splunk/semantic-release-action@v1.2
        with:
          semantic_version: 20
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  update-semver:
    name: Move Repository semver tags
    if: startsWith(github.ref, 'refs/tags/v')
    needs: new-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-update-semver@v1
