name: Release
on:
  push:
    branches:
      - main

jobs:
   new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Semantic Release
        id: semantic
        run: |
          npm install -D @semantic-release/changelog @semantic-release/git @semantic-release/exec
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
